# Generated by Django 4.0.3 on 2022-03-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(help_text='if blank, a random password will be generated.', max_length=16)),
                ('birthdate', models.DateField(help_text='format: dd/mm/yyyy', max_length=10)),
            ],
        ),
    ]
