# Generated by Django 4.0.3 on 2022-03-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='zytYh(9SXpnu#jL6', help_text='if blank, a random password will be generated.', max_length=16),
        ),
    ]
